### ISSUE TITLE
KG localhost connection

### ISSUE THREAD

**Issue by rajharshiitb** [ajesujoba/UNIQORN#1]
class CLOCQ:
	def __init__(self, host="http://localhost", port="7777"):
		self.host = host
		self.port = port
		self.req = requests.Session()

To what we are connecting to? Is localhost running some CLOCQ code?

**Comment by ajesujoba** [comment]
Hi @rajharshiitb, 

CLOCQ is an API and you can find more details about it [here](https://clocq.mpi-inf.mpg.de/)

**Comment by rajharshiitb** [comment]
Thanks got it.
